"""Added customer and serial_no columns to Summary table.

Revision ID: 2547b65e3c8e
Revises: 
Create Date: 2015-03-13 09:18:04.987302

"""

# revision identifiers, used by Alembic.
revision = '2547b65e3c8e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary', sa.Column('customer', sa.String(), nullable=True))
    op.add_column('summary', sa.Column('serial_no', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summary', 'serial_no')
    op.drop_column('summary', 'customer')
    ### end Alembic commands ###
