"""Added array_name, flare_version, lun_capacity, and disk_capacity columns to Summary table

Revision ID: 4bbe4c31479
Revises: 5354d1ae375e
Create Date: 2015-03-15 18:43:49.319788

"""

# revision identifiers, used by Alembic.
revision = '4bbe4c31479'
down_revision = '5354d1ae375e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary', sa.Column('disk_capacity', sa.String(), nullable=True))
    op.add_column('summary', sa.Column('flare_version', sa.String(), nullable=True))
    op.add_column('summary', sa.Column('lun_capacity', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summary', 'lun_capacity')
    op.drop_column('summary', 'flare_version')
    op.drop_column('summary', 'disk_capacity')
    ### end Alembic commands ###
