"""Added arrayname column to Summary table

Revision ID: 5354d1ae375e
Revises: 2547b65e3c8e
Create Date: 2015-03-15 06:31:23.047791

"""

# revision identifiers, used by Alembic.
revision = '5354d1ae375e'
down_revision = '2547b65e3c8e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary', sa.Column('array_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summary', 'array_name')
    ### end Alembic commands ###
